# Generated by Django 4.0.2 on 2022-03-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=200)),
                ('gameDesc', models.CharField(max_length=200)),
                ('masterName', models.CharField(max_length=200)),
            ],
        ),
    ]
